CC = gcc
CFlags = –Wall

#SRC=$(wildcard *.c)

#test: $(SRC)
#	gcc -o $@ $^ $(CFLAGS) 

copy:
	$(CC) -o cfcopy cfcopy.c

linecopy:
	$(CC) -o lfcopy lfcopy.c

linecount:
	$(CC) -o lcount lcount.c

wordcount:
	$(CC) -o wcount wcount.c

printword:
	$(CC) -o genword genword.c