CC = gcc
CFlags = –Wall

#SRC=$(wildcard *.c)

#test: $(SRC)
#	gcc -o $@ $^ $(CFLAGS) 

copy:
	$(CC) -o cfcopy.out cfcopy.c

linecopy:
	$(CC) -o lfcopy.out lfcopy.c

linecount:
	$(CC) -o lcount.out lcount.c

wordcount:
	$(CC) -o wcount.out wcount.c

printword:
	$(CC) -o genword.out genword.c